staking/app/scripts/devnet_upgrade.ts, staking/programs/staking/src/lib.rs, staking/tests/clock_api_test.ts
One thing we had in clickup was to make sure we didn't deploy with mock clock enabled. We had the runtime check, but it wasn't obvious how to do it at deploy time. This solves that problem.
The rust compiler is pretty aggressive and will delete variables that are not referenced, so this bogus assert was the best I could come up with. Declaring a constant string did not work.
=> Extra mock clock check

staking/programs/staking/src/lib.rs
This new clippy warning was raising warnings on `AnchorError`.
=> Allow large errors

staking/Cargo.lock, staking/app/deploy/1_create_realm.ts, staking/app/deploy/2_create_governance.ts, staking/app/deploy/3_init_staking.ts, staking/app/deploy/create_governance.ts, staking/app/deploy/create_realm.ts, staking/app/deploy/init_staking.ts, staking/app/deploy/mainnet_beta.ts, staking/programs/staking/Cargo.toml, staking/programs/staking/src/lib.rs
Current parameters :
There is one governance key (doesn't control anything yet) with parameters, this key is intended for upgrading the staking program and governance program :
- Proposals are 7 days
- Starting a proposal requires 1% of the supply
- Passing a proposal requires 50% of the locked supply to vote yes.
- Proposal will be finalized as soon as 50% of the locked supply votes yes without needing to wait until the end of the voting period.
- No hold up time (proposal can be executed as soon as it passes)
Staking program parameters :
- Pyth epoch : 7 days
- Cooldown period : 1 full epoch
=> Deploy mainnet

frontend/components/Header.tsx, frontend/pages/staking.tsx
use dynamic import to fix hydration errors
=> fix hydration errors

staking/app/StakeConnection.ts, staking/app/scripts/localnet.ts, staking/programs/staking/src/context.rs, staking/programs/staking/src/error.rs, staking/programs/staking/src/lib.rs, staking/programs/staking/src/state/global_config.rs, staking/programs/staking/src/state/stake_account.rs, staking/target/idl/staking.json, staking/target/types/staking.ts, staking/tests/config.ts, staking/tests/staking.ts, staking/tests/utils/before.ts, staking/tests/vesting_test.ts
Adds an intruction join_dao_lcc where the user needs to sign a hash of the DAO LLC agreement.
This agreement needs to be signed before the user is able to vote or stake.
=> Add llc agreement

staking/app/StakeConnection.ts, staking/app/deploy/4_transfer_authorities_to_multisig.ts, staking/tsconfig.api.json, staking/tsconfig.json
I prefer using the locally generated IDL than the on-chain IDL. 
It feels more secure since the on-chain IDL can be upgraded.
Explorer will still use the on-chain IDL.
=> Use local idl

staking/programs/staking/src/context.rs, staking/programs/staking/src/lib.rs, staking/target/idl/staking.json, staking/target/types/staking.ts, staking/tests/config.ts
I need this code to transfer the PDA authority to the actual key.
=> Transfer pda authority

staking/programs/staking/src/error.rs, staking/programs/staking/src/lib.rs, staking/programs/staking/src/state/positions.rs, staking/programs/staking/src/state/vesting.rs, staking/target/idl/staking.json, staking/target/types/staking.ts
two changes per our conversation:
1. disallow splitting accounts that have positions. This means you have to unstake before you can split.
2. test the vesting account splitting logic.
I didn't add the check that all tokens in the account are locked because it turns out that check doesn't help with the vesting account splitting logic.
=> Split accounts test

staking/app/deploy/3_create_governance.ts
Just updating the create governance script for the current deployment
=> Update governance script

frontend/pages/api/getPythTokenBalance.ts
The previous call getTokenAccountsByOwner is expensive RPC-wise
=> Remove expensive call to fetch tokens

staking/app/PythClient.ts, staking/app/StakeConnection.ts, staking/package.json
Just a cleanup refactor for better integration with realms UI
=> Refactor pyth client

frontend/pages/api/v1/all_locked_accounts.ts, frontend/pages/api/v1/locked_accounts.ts
This is an API that returns the total amount locked. 
It might be useful for Coinmarketcap or for other people to verify the locked supply.
Example call : https://staking-git-all-locked-api-pyth-web.vercel.app/api/v1/all_locked_accounts
=> All locked api

staking/app/StakeConnection.ts
The error inside `wasm.getUnvestedBalance` was not showing in Toast. I handle it and put a better text so that the user undertands better the error.
=> Handle wasm error better

frontend/pages/create_locked_account.tsx, staking/app/pythBalance.ts
- Add toast for feedback on whether the transaction went through or failed.
- Ignore spaces and double quotes for Pyth Balance
=> Improve create locked account page

frontend/hooks/useJoinDaoLlcMutation.ts, staking/app/StakeConnection.ts
Reset some queries in useJoinDaoLlcMutation so the modal doesn't pop when you deposit or stake right after signing
=> Fix useJoinDaoLlcMutation

frontend/pages/approve.tsx, frontend/pages/request.tsx, staking/app/StakeConnection.ts
Refactor accept transfer
Add feature to be compatible with someone having multiple accounts
=> Accept transfer

staking/app/StakeConnection.ts, staking/package.json
In the Pyth Realm only staked tokens can vote and the voting power of each staked token is inversely proportional to how many tokens are currently staked (so that at any time the sum of the power of all staked tokens is equal to the total voting power of 10 Billion).
In the UI, voting power gets displayed, leading to a lot of confusion in the DAO.
It would be better to do a change of unit and display things as the number of staked tokens.
This PR is exposing the scaling factor.
=> Add scaling factor to convert from voter weight to staked tokens

frontend/utils/validAmountChange.ts
This regex error was making it impossible to stake more than `999999` tokens at a time unless you added decimals.
=> [frontend] Fix balance regex

frontend/next.config.js, frontend/package.json, frontend/pages/api/getAllStakingAccounts.ts, frontend/pages/api/v1/all_locked_accounts.ts, frontend/pages/api/v1/cmc/supply.ts, frontend/pages/api/v1/locked_accounts.ts, package-lock.json, staking/app/api_utils.ts, staking/app/constants.ts, staking/app/index.ts, vercel.json
The large volume of new stake accounts has broken the API for the total number of locked tokens.
The goals of this PR are :
- refactor a bunch of functions used in the APIs into `api_utils.ts`
- create a new implementation of `getAllStakeAccounts` that is more efficient
It still don't works but I think it's in a reviewable state
=> [frontend] Try to fix API

staking/app/StakeConnection.ts, staking/tests/split_vesting_account.ts, staking/tests/vesting_test.ts
Squads has trouble handling ephemeral keypairs, so I replaced the ephemeral keypair when creating an account with a seeded account.
=> [frontend] Fix Squads compatibility

docs/pips/pip-1.md, staking/app/scripts/snapshot.ts
The script was failing with a very vague error from zstd-js library. This change will properly initializes it to fix the issue.
=> fix: initialize zstdinit properly

staking/app/StakeConnection.ts
Some users that are unstaked can't request splits because they have deactivated positions. This is meant to fix it.
=> feat: cleanup position before split request

staking/app/StakeConnection.ts
With the step that cleans up positions the compute cap sometimes gets exceeded.
I'm reducing the compute unit price so that the cost remains similar.
=> fix: remove compute cap

frontend/pages/api/v1/cmc/supply.ts, staking/app/api_utils.ts
This will make the `api/v1/cmc/supply` endpoint robust as it no longer uses the hardcoded list of locked accounts.
=> feat: make circulating supply robust

staking/programs/staking/src/lib.rs
The SplitWithStake error message for accounts with staked tokens has been replaced with RecoverWithStake. This change is reflected in the lib.rs file under the recover account function. This implementation guards against the possibility of double voting that could occur if an account with staked tokens were allowed to be transferred.
=> fix: use the correct error in the recover account

package-lock.json, staking/.dockerignore, staking/.gitignore, staking/Dockerfile, staking/scripts/build_verifiable_staking_program.sh
This change adds a Dockerfile based on Anchor's default verifiable build dockerfile and a script to build the program using that Dockerfile. The script also prints the sha256sum of the program which can be used to verify on-chain deployments.
=> feat: add verifiable staking build script

staking/app/StakeConnection.ts
There's currently a bug that for accounts that have reached the maximum number of positions the Unstake button doesn't work.
This is because sometimes when closing a position the position gets closed partially and a new position gets created with the rest of the balance. If the maximum number of positions has been attained, it will fail with `TooManyPositions`.
We need to avoid this behavior in the sdk when the maximum number of position has been attained. The solution is if the maximum number of positions has been attained we "round down" the amount unstaked and avoid closing a position partially.
=> chore: support max capacity unstake

staking/app/StakeConnection.ts
Throw an error in https://github.com/pyth-network/governance/pull/429 when it won't unstake any tokens.
=> fix: error message when unlocking too little coins in full capacity

.github/workflows/test-frontend.yaml
When I set up #442 , I didn't take into account that the staking package must be built before running type checks.
This PR fixes that so that the CI type checks work correctly.
=> Make sure the staking package is built before checking types

frontend/pages/_app.tsx
Some users have requested to test the devnet instance with WalletConnect.
Currently WalletConnect is hardcoded with Solana mainnet, hopefully this solves their issues.
=> fix: wallet connect for devnet

.prettierignore, frontend/hooks/useStakeConnection.ts, frontend/pages/test.tsx
I want to add priority fees.
Browser wallets (Phantom) normally add priority fees to transactions created by the frontend.
This is not the case however for WalletConnect integrations like many custody providers.
Therefore I want to turn on a small priority fee so WalletConnect integrations can interact better with this frontend.
=> feat: add priority fees

staking/programs/integrity-pool/src/context.rs, staking/programs/integrity-pool/src/error.rs, staking/programs/integrity-pool/src/lib.rs, staking/programs/integrity-pool/src/state/pool.rs, staking/programs/integrity-pool/tests/integrity_pool_slash.rs, staking/programs/integrity-pool/tests/utils/integrity_pool/slash.rs
This pr makes the calculation of the slash events to be on a per publisher basis. The indexes, seeds, and num counters are stored separately per publisher now.
=> feat: make slash events separated for publishers

staking/integration-tests/src/utils/error.rs, staking/integration-tests/tests/advance.rs, staking/integration-tests/tests/delegate.rs, staking/integration-tests/tests/initialize_pool.rs, staking/integration-tests/tests/integrity_pool_slash.rs, staking/integration-tests/tests/max_positions.rs, staking/integration-tests/tests/merge_delegation_positions.rs, staking/integration-tests/tests/set_publisher_stake_account.rs, staking/integration-tests/tests/staking_slash.rs
This PR refactors the `assert_anchor_program_error` to `assert_anchor_program_error!` macro for the following reasons.
1. When the assert fails it now shows exactly which one failed, instead of referring to the inside of the fuction.
2. It's more aligned with other asserts that are all macros.
=> refactor: make assert_anchor_error a macro

staking/integration-tests/src/publisher_caps/utils.rs, staking/integration-tests/tests/advance.rs, staking/integration-tests/tests/delegate.rs, staking/programs/integrity-pool/src/error.rs, staking/programs/integrity-pool/src/state/pool.rs
This is a bug. People could stake to 0 pubkey, writing data to free publisher slots.
=> fix: forbid zero pubkey

frontend/package-lock.json
When we merged the new changes to the staking program and we started using the npm version of `@pythnetwork/staking-wasm` and `@pythnetwork/staking` in the frontend, the npm version of `@pythnetwork/staking-wasm` actually outdated.
I'm fixing this by making a new release of `@pythnetwork/staking-wasm` from https://github.com/pyth-network/governance/tree/pyth-staking-v2.3.0 and using it in main.
=> [chore] bump wasm version

.vscode/settings.json, staking/Cargo.lock, staking/integration-tests/Cargo.toml, staking/integration-tests/src/integrity_pool/helper_functions.rs, staking/integration-tests/src/integrity_pool/instructions.rs, staking/integration-tests/src/publisher_caps/helper_functions.rs, staking/integration-tests/src/publisher_caps/utils.rs, staking/integration-tests/src/setup.rs, staking/integration-tests/src/solana/instructions.rs, staking/integration-tests/src/solana/utils.rs, staking/integration-tests/src/staking/helper_functions.rs, staking/integration-tests/src/staking/instructions.rs, staking/integration-tests/src/staking/pda.rs, staking/integration-tests/tests/advance.rs, staking/integration-tests/tests/claim.rs, staking/integration-tests/tests/delegate.rs, staking/integration-tests/tests/initialize_pool.rs, staking/integration-tests/tests/integrity_pool_slash.rs, staking/integration-tests/tests/max_positions.rs, staking/integration-tests/tests/merge_delegation_positions.rs, staking/integration-tests/tests/set_publisher_stake_account.rs, staking/integration-tests/tests/stability.rs, staking/integration-tests/tests/staking_slash.rs, staking/integration-tests/tests/voting.rs, staking/programs/integrity-pool/src/context.rs
This PR adds a new test to check the stability of the integrity pool program after running a set number of random operation. It is disabled by default since it will take a long time to run.
=> feat: add stability test

frontend/pages/approve.tsx
Before this we would use `stakeConnection.getStakeAccounts` which would load tons of accounts and lead to rate limiting in by the rpc. Instead we only need to load the data from the currently selected account.
=> fix: optimize account calls in approve

staking/programs/staking/src/lib.rs, staking/programs/staking/src/state/positions.rs, staking/programs/staking/src/utils/risk.rs, staking/tests/max_pos.ts, staking/tests/position_lifecycle.ts
We can withdraw without cleaning.
For that I just need to update `validate` to ignore Unlocked positions.
We also need to update slashing since governance exposure no longer counts unlocked positions, so we ignore unlocked positions when we adjust positions in `slash_account`
=> feat: allow withdrawing without cleaning

staking/programs/integrity-pool/src/state/pool.rs
This refactor will allow me to access `total_eligible_delegation` in the main loop. I will use that to compute claimed_rewards.
=> feat: refactor reward logic in advance

frontend/pages/approve.tsx, frontend/pages/request.tsx
Like https://github.com/pyth-network/governance/pull/504 for requesting. We avoid loading all stake accounts at the same time.
=> fix: don't load all accounts at the same time in request

staking/cli/src/cli.rs, staking/cli/src/instructions.rs, staking/cli/src/main.rs, staking/programs/integrity-pool/src/lib.rs
Adding a bunch of instructions that I needed while configuring the program
=> feat: expand cli

staking/Cargo.lock, staking/cli/Cargo.toml, staking/cli/src/cli.rs, staking/cli/src/instructions.rs, staking/cli/src/main.rs
Add close publisher caps functionality.
Close publisher caps and vaa in advance.
=> feat: close publishers cli

staking/programs/staking/src/state/positions.rs
**Fix Typo in `positions.rs`**
This pull request addresses a minor typo in the `positions.rs` file, improving the accuracy and readability of the code comments.
- **File Modified:** `staking/programs/staking/src/state/positions.rs`
- **Summary of Changes:**
- Corrected "futher" to "further" in the comment describing epoch state checks.
This change helps maintain precise documentation for developers reviewing the epoch state logic and position state equivalence criteria.
---
**Allow edits by maintainers:** [x]
=> **Fix Typo in `positions.rs`**

staking/cli/src/instructions.rs
The script to advance stopped working after we added compute units
=> fix: reduce step to allow compute unit instructions
