pyth-network/governance

- staking/app/StakeConnection.ts
- staking/app/deploy/init_staking.ts
- staking/package.json
We need to renable maxVoterWeightRecord in the api basically.
> Restore max voter weight

- staking/app/StakeConnection.ts
- staking/app/constants.ts
- staking/package.json
I need to update the package before we update the frontend. Will release after merging.
> Add mainnet constants

- staking/Anchor.toml
- staking/app/PythClient.ts
- staking/app/constants.ts
- staking/app/deploy/1_create_realm.ts
- staking/app/deploy/3_init_staking.ts
- staking/app/deploy/devnet.ts
- staking/app/deploy/mainnet_beta.ts
- staking/app/scripts/devnet_upgrade.ts
- staking/programs/staking/src/lib.rs
The goal of this PR is having the same address for the staking program in all 3 networks. This reduces the number of magic pubkeys.
> Cleanup staking address, now it is the same across all 3 networks

- metrics/governance_metrics.ts
- staking/Anchor.toml
- staking/app/StakeConnection.ts
- staking/app/constants.ts
- staking/app/deploy/1_create_realm.ts
- staking/app/deploy/2_create_governance.ts
- staking/app/deploy/3_init_staking.ts
- staking/app/deploy/devnet.ts
- staking/app/deploy/mainnet_beta.ts
- staking/package.json
- staking/programs/staking/src/lib.rs
- staking/programs/staking/src/wasm.rs
- staking/wasm/package.json
- staking/yarn.lock
Ok, so the goal now is having the same governance address everywhere. 
I decided to add it to wasm -> only downside is now `GOVERNANCE_ADDRESS` is a function
> Cleanup governance address

- staking/app/deploy/4_transfer_authorities_to_multisig.ts
- staking/app/deploy/devnet.ts
- staking/app/deploy/mainnet_beta.ts
Add migration script to give keys to multisig.
> Transfer keys to multisig

- .github/workflows/anchor.yml
- .github/workflows/prettier.yml
- .github/workflows/rustfmt.yml
> Remove comments

- .github/workflows/anchor.yml
- .github/workflows/clippy.yml
- .github/workflows/metrics_deploy.yml
- .github/workflows/prettier.yml
- .github/workflows/rust.yml
- .github/workflows/rustfmt.yml
I changed the default branch to be main, these workflows need to be updated
> Update workflows to work with the main branch

- staking/app/StakeConnection.ts
Add some code to delete old positions and make room in the postion account.
Whenever we try to create a new position, we look for expired positions and delete them using `ClosePosition`
> Make the change

- staking/programs/staking/src/state/stake_account.rs
This will make us more nimble if we want to add fields since we won't have to resize accounts
> Add extra space in case we need to add fields

- package-lock.json
- staking/app/deploy/ledger.ts
- staking/package.json
Porting LedgerNodeWallet from `pyth-crosschain` to make writing scripts easier
> Add ledger

- staking/tests/utils/before.ts
CI was brittle after only waiting for 10 seconds
> Increase validator retries

- frontend/components/Header.tsx
Now that our code is merged in realms.today
> Update governance url

- frontend/components/modals/LockedModal.tsx
- frontend/components/modals/UnstakedModal.tsx
- frontend/components/panels/StakePanel.tsx
- frontend/components/panels/UnstakePanel.tsx
> Add more info

- staking/app/StakeConnection.ts
The previous array comparison didn't work
> Fix isLlcAgreement

- frontend/components/panels/WithdrawPanel.tsx
The onAction wasn't using the most up to date "amount"
This was preventing people from withdrawing.
> Fix withdraw bug

- frontend/pages/api/v1/locked_accounts.ts
Someone complained about this endpoint caching. So I'm turning it off.
> Remove caching

- frontend/pages/api/v1/cmc/supply.ts
The import was crashing because `@pythnetwork/staking/app/deploy/mainnet_beta` loads a key from the hard drive.
I just hardcode PYTH_TOKEN instead.
> [Coinmarketcap] FIx bug

- frontend/pages/request.tsx
A UI for people to be able to request a locked token transfer
> [frontend] Request locked token transfer UI

- frontend/hooks/useSplitRequest.ts
- frontend/pages/approve.tsx
- frontend/pages/create_locked_account.tsx
- frontend/pages/request.tsx
Use hooks:
- `useStakeConnection`
- `useStakeAccounts`
Make new hook:
- `useSplitRequest`
This addresses the comments from https://github.com/pyth-network/governance/pull/310
> [Transfer locked tokens] use hooks

- frontend/pages/approve.tsx
This text got copied over from request.tsx
> Update approve text

- .github/workflows/publish-staking.yml
- staking/package.json
I want to bump before publishing it to npm
> Bump @pythnetwork/staking staking for publishing

- frontend/components/modals/LockedModal.tsx
- frontend/hooks/useBalance.ts
I think this refactor is cleaner and will be useful for other changes I want to make
> [frontend] Refactor Locked Tokens Modal

- frontend/components/modals/LockedModal.tsx
Just a text update for partial staking
> [frontend] Update locked token text

- docs/constitution/pyth-dao-constitution.md
- Added operations wallet for PIP submission and adjusted membership counts and voting ratios
- md styling fixes
> added operations wallet

- frontend/hooks/useProfile.ts
- frontend/hooks/useProfileConnection.ts
- frontend/hooks/useUpdateProfileMutation.ts
- frontend/pages/index.tsx
- frontend/pages/profile.tsx
Moving some things around to match current structure of the hooks
> Profile refactor

- staking/app/scripts/snapshot.ts
This PR adds a timestamp to the output of the staker snapshot scripts.
> Add timestamp

- docs/councils/pricefeed/election/name-protocol.md
- docs/councils/pythian/election/name-protocol.md
folder structure and stub templates for candidacy
> council candidacy templates

- .prettierignore
- staking/.gitignore
- staking/app/StakeConnection.ts
- staking/app/scripts/snapshot.ts
Add the first time a user staked to the snapshot tool
> [snapshot] Add time of first stake

- docs/councils/pythian/election/Marc Tillement - Pyth Data Association.md
> marc-pythdataassociation

- docs/pips/operational/op-pip-1.md
- docs/pips/operational/op-pip-2.md
- Replace http://xc-admin.xyz.pyth.network/ by https://proposals.pyth.network/
- Make proposal ids more explicit
- Improve text
> fix: cleanup pips

- docs/councils/price-feed/election/Lawrence-NOBI.md
Submit my candidacy to Price Feed Council
> Added Lawrence-NOBI.md

- docs/pips/operational/op-pip-1.md
- docs/pips/operational/op-pip-2.md
- docs/pips/operational/op-pip-3.md
- docs/pips/operational/op-pip-4.md
- docs/pips/operational/op-pip-5.md
- docs/pips/operational/op-pip-6.md
- docs/pips/operational/op-pip-7.md
And also add op number to the md files.
> docs: add op-pip-7

- docs/pips/constitutional/pip-2.md
- docs/pips/operational/op-pip-9.md
- run pre-commit
- fix names of proposal accounts for pip9
> fix: op-pip9

- staking/programs/integrity-pool/src/context.rs
- staking/programs/integrity-pool/src/error.rs
- staking/programs/integrity-pool/src/lib.rs
- staking/programs/integrity-pool/src/state/mod.rs
- staking/programs/integrity-pool/src/state/pool.rs
- staking/programs/integrity-pool/src/state/slash.rs
- staking/programs/integrity-pool/src/utils/constants.rs
- staking/programs/integrity-pool/tests/integrity_pool_slash.rs
- staking/programs/integrity-pool/tests/utils/integrity_pool/mod.rs
- staking/programs/integrity-pool/tests/utils/integrity_pool/slash.rs
This PR introduces create slash event instruction for integrity pool program, it will store necessary data for slashing. The actual slashing instruction will be implemented in future PRs.
> feat: add integrity pool create slash event

- staking/Cargo.lock
- staking/programs/integrity-pool/Cargo.toml
- staking/programs/integrity-pool/src/error.rs
- staking/programs/integrity-pool/src/lib.rs
- staking/programs/integrity-pool/src/state/pool.rs
- staking/programs/integrity-pool/tests/advance.rs
- staking/programs/integrity-pool/tests/utils/publisher_caps/post_publisher_caps.rs
- staking/programs/publisher-caps/Cargo.toml
- staking/programs/publisher-caps/src/lib.rs
Actual implementation of the publisher caps program.
In the tests, I just replaced post_publisher_caps by the new implementation and everything is passing
> feat: publisher caps program

- staking/programs/staking/src/state/positions.rs
This proptest always failed on some edgecases like when two positions in the vector were identical. I am fixing it.
> fix: proptest

- staking/integration-tests/tests/staking_slash.rs
- staking/programs/staking/src/lib.rs
- staking/programs/staking/src/state/positions.rs
- staking/programs/staking/src/state/target.rs
> test: slash_account prop test

- staking/cli/src/cli.rs
- staking/cli/src/instructions.rs
- staking/cli/src/main.rs
- staking/integration-tests/src/integrity_pool/helper_functions.rs
- staking/integration-tests/src/integrity_pool/instructions.rs
- staking/integration-tests/tests/integrity_pool_slash.rs
- staking/programs/integrity-pool/src/context.rs
- staking/programs/integrity-pool/src/error.rs
- staking/programs/integrity-pool/src/lib.rs
- staking/programs/integrity-pool/src/state/pool.rs
Didn't add a function to modify it because reward_authority shouldn't be able to update this
> feat: enforce slash custody

- staking/integration-tests/src/integrity_pool/instructions.rs
- staking/integration-tests/tests/advance.rs
- staking/integration-tests/tests/set_publisher_stake_account.rs
- staking/programs/integrity-pool/src/context.rs
- staking/programs/integrity-pool/src/lib.rs
Adds some logic for publishers to opt-out of delegation rewards.
> feat: allow pub to opt out

- .github/workflows/anchor.yml
- .github/workflows/clippy.yml
- staking/Cargo.lock
- staking/cli/Cargo.toml
- staking/cli/src/cli.rs
- staking/cli/src/instructions.rs
- staking/cli/src/main.rs
Adds ledger support to the CLI
> feat: add ledger

- staking/cli/src/instructions.rs
> fix: create snapshots directory if it doesn't exist

- .github/workflows/staking_snapshot.yml
- staking/Cargo.lock
- staking/cli/Cargo.toml
- staking/cli/src/instructions.rs
- staking/package.json
- staking/scripts/staking_snapshot.js
- generate snapshot in both csv and json files
- insert snpashot data into an external database
> feat: generate staking snapshot and save it to json file
